basePath: /api/v1
definitions:
  schemas.ProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    required:
    - description
    - name
    - price
    - stock
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a example GO API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger GO API
  version: "1.0"
paths:
  /product:
    post:
      consumes:
      - application/json
      description: Create a new product with name, description, price, and stock
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/schemas.ProductRequest'
      produces:
      - application/json
      responses: {}
      summary: Create a new product
      tags:
      - Products
  /status/health:
    get:
      consumes:
      - application/json
      description: Responds with a hello message from the Product Controller
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Greets from Product Controller
      tags:
      - Status
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
